amcl:
  use_map_topic: true
  first_map_only: true
  min_particles: 100
  max_particles: 2000
  laser_min_range: -1.0
  laser_max_range: 10.0
  laser_max_beams: 60
  odom_frame_id: "odom"
  base_frame_id: "base_link"
  global_frame_id: "map"
  update_min_d: 0.1
  update_min_a: 0.1
  odom_model_type: "diff-corrected"
