DWAPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 0.3
  min_vel_theta: -0.3
  acc_lim_theta: 0.8
  acc_lim_x: 0.5
  acc_lim_y: 0.2
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  sim_time: 1.0
  vx_samples: 20
  vtheta_samples: 20
